### ISSUE TITLE
[Question] creating frontend service

### ISSUE THREAD

**Issue by shalastra** [ivangfr/springboot-keycloak-mongodb-testcontainers#1]
First of all, you have done a great job with this repository., many things became clear for me regarding keycloak. 
You seem as a knowledgable person in the keycloak topic. I'm trying to create similar integration, but in my case I want to have public frontend and confidential/bearer-only backend. I have tried to create two keycloak clients, however the token is not passed between services. Maybe you had the similar issue? 

I'm not sure if this is a place to ask that kind of question.

**Comment by ivangfr** [comment]
Hi @shalastra , thanks for the message. It is ok to ask here, no problem at all.

I didn't get exactly what you wanted to say in this phrase, _"the token is not passed between services"_? Here, 1) you want to say that the token is not passed from the frontend application to the backend application or 2) the token is not shared between the two Keycloak clients?

**Comment by shalastra** [comment]
I'm not sure yet, but I would say the second option is more likely.

**Comment by ivangfr** [comment]
Old versions of Keycloak didn't provide clustering out-of-the-box. That is why, I needed to create the [`keycloak-clustered`](https://github.com/ivangfr/keycloak-clustered) that extends Keycloak docker images.

In the repository, [`docker-swarm-enviroment > keycloak-clustered`](https://github.com/ivangfr/docker-swarm-environment/tree/master/keycloak-clustered-mode), I did an experiment with `keycloak-clustered` using `a cluster of docker engines in swarm mode`.

Nowadays, the latest versions of Keycloak provide clustering out-of-the-box. I haven't tried them yet, but I think this [link](https://www.keycloak.org/2019/05/keycloak-cluster-setup.html) can help.

**Comment by ivangfr** [comment]
@shalastra I have created a new Keycloak Docker Image based on the official Keycloak Docker Image. With this new one, we can create easily a Keycloak cluster. If you want to try, that is the image in Docker Hub https://hub.docker.com/r/ivanfranchin/keycloak-clustered.

In the README, there are two examples: one explains how to run it in the same host using `PING` discovery protocol; another, explains how to run it in different hosts using `JDBC_PING` discovery protocol. In the last example, I am using a cluster of Docker Engines in swarm mode.

**Comment by ivangfr** [comment]
@shalastra can I close this issue?

**Comment by shalastra** [comment]
@ivangfr yes, thank you for your help.
